### PR TITLE
Add Windows MSVC support

### PR DESCRIPTION
**Pull request by Systemcluster**

### CODE REVIEW

**Comment by danieldk** [comment]
Looks good, any chance you could also add Windows to CI?

**Comment by Systemcluster** [comment]
I've changed the test workflow to run on Windows, Ubuntu and macOS, and also added test runs for both `+crt-static` and `-crt-static` target features (since that caused me some pain getting the CMake flags right in the Windows build).

I had to regenerate `bindings.rs` because it contained a bunch of macOS- and pthreads-specific binding and test code. I don't know what caused bindgen to generate those before, but as far as I can see it should now work on all systems.

**Comment by Systemcluster** [comment]
Should be good to go 👍

**Review by danieldk — APPROVED** [review]

**Comment by danieldk** [comment]
Thanks a lot! I'll try to make a new release this weekend.

**Pull request merged**
